---

platforms:
- name: vagrant-ubuntu-12.04
  driver_plugin: vagrant
  driver_config:
    box: canonical-ubuntu-12.04
    box_url: http://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-amd64-vagrant-disk1.box
    require_chef_omnibus: true
  attributes: {bluepill: { bin: "/usr/local/bin/bluepill" }}
- name: rackspace-ubuntu-12.04
  driver_plugin: rackspace
  driver_config:
    image_id: e4dbdba7-b2a4-4ee5-8e8f-4595b6d694ce
    require_chef_omnibus: true
  attributes: {bluepill: { bin: "/opt/chef/embedded/bin/bluepill" }}

suites:
- name: default
  run_list: ["recipe[apt]", "recipe[teamcity_server_test]"]
